### ISSUE TITLE
Don't support import syntax which will be converted to 'require()' by babel?

### ISSUE THREAD

**Issue by tetsuharuohzeki** [power-assert-js/babel-plugin-empower-assert#3]
## Summary

Could this plugin support the case to use import syntax to load `assert`?

``` javascript
import * as assert from 'assert'; 

assert.ok(true);
```
## env
- Node v5.10
- babel-plugin-empower-assert 1.2.0

**Comment by twada** [comment]
@saneyuki Thanks!
Fair request. I'll implement it.

**Comment by tetsuharuohzeki** [comment]
@twada Thank you for your rapid response!

**Comment by twada** [comment]
Just released [babel-plugin-empower-assert 1.3.0](https://github.com/power-assert-js/babel-plugin-empower-assert/blob/master/CHANGELOG.md#130-2016-04-27)
